### ISSUE TITLE
No dataset present

### ISSUE THREAD

**Issue by nitinkumar30** [khelvn/jupyter-notebook#1]
As provided in the projects, dataset files haven't been provided. Atleast, provide link of the dataset being used. Thanks.

**Comment by khelvn** [comment]
Hi @nitinkumar30, I have uploaded the datasets to the repo. I'm also including a link below incase you need it.

https://www.kaggle.com/datasets/shivamb/netflix-shows/code -> then proceed to click the download button at the top right section.

or (for direct download link)

https://storage.googleapis.com/kaggle-data-sets/434238/2654038/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20240611%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240611T101451Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=2720b1dda2d01f38f3a057b62e4252ff9cdbe488b73f1d3354cb17c259d77f3e8df67c590fe17a2775965a4fef769208699b380439167fae362394590bc230561795d5e2e278aabba02f5ba29ef425723acea79b2c71986d4c9ef8217589d5ae62166efb50de16e8e36365bd3e19a9556a9b4efd558f029d0b8811601dd3ffa86ed304d75c9e38f53f5e5fd4197a6d3b0bc0fccb4342855b4cf10caa3824a6fea92d056b115a888960f9f11f517b218d713414b770a410e80cfe6a2174fb79e4cfbfb2f05f86e3137675ed84cbf5fcf47be1c4fe56ff2db456cb086cc82a10a73bba16a3657bc2c757daf3b3fad1a57ece2bf10d45aafef380953311b164c85a

**Comment by nitinkumar30** [comment]
Thank you for the download link as well @khelvn . I'm able to download the dataset now. However, it was only for Netflix project I guess. Please correct me if I'm wrong.

**Comment by khelvn** [comment]
@nitinkuymar30 yes, the link is so for just the Netflix project. 
You can download the nestle dataset from this Repo
